# DEFAULT parameter file for running wakeflow, HD 163296 parameters as example, set to run mcfost

run_info:
    name: "inner_wake"                           # give your run a name (results are saved a directory called this, don't use spaces)
    system: "inner_wake"                         # name of the system you are modelling

disk:
    m_star: 1.9                                  # mass of central star in solar masses
    m_planet: [1.34]                              # mass of embedded planet(s) in Jupiter masses (list or float)
    r_outer: 500                                 # outer radius of disk in au
    r_inner: 100                                 # inner radius of disk in au (does not apply for Cartesian grid)
    r_planet: 270                                # orbital radius of embedded planet in au
    r_ref: 270                                   # reference radius R0 for H/R
    r_c: 0                                       # critical radius for exponentially tapered density profile. set to 0 for power law
    q: 0.25                                      # q index, defined as c_s \propto R^{-q}
    p: 1.0                                       # p index, defined as rho \propto R^{-p} or \propto R^{-p}*\exp{-R/r_c}^{2-p}
    hr: 0.10                                     # disc flaring H/R at R0
    dens_ref: 1                                  # rho at R0 in g/cm^3, unimportant for mcfost as it rescales
    cw_rotation: True                            # CURRENTLY DOES NOTHING, you will get anticlockwise and be pleased about it :-) (bool)

angles:
    inclination: -225                            # inclination of disk in degrees    (46.7)
    PA: 45                                       # position angle of disk in degrees    (133.3)
    PAp: 45                                      # planet_az    (currently azimuthal angle FROM the PA)

grid:
    type: "cartesian"                            # "cylindrical" or "cartesian" or "mcfost" -- must choose mcfost to write fits file
    n_x: 400                                     # number of x grid points
    n_y: 400                                     # number of y grid points
    n_r: 200                                     # number of r grid points
    n_phi: 160                                   # number of phi grid points
    n_z: 50                                      # number of z grid points
    r_log: False                                 # use logarithmic scale for r points (boolean) -- ignored for mcfost grid

plotting:
    make_midplane_plots: True                    # create midplane plots of velocity components and density
    show_midplane_plots: True                    # show plots as code runs
    show_teta_debug_plots: False                 # show t, eta space plots (including putting the linear solution into t,eta)

results:
    include_planet: True                         # include perturbations from a planet? (lets you run an unperturbed disk) (bool)
    include_linear: True                         # include the results from the linear regime?
    save_perturbations: True                     # save perturbations to npy file
    save_total: True                             # save background + perturbations to npy file
    write_FITS: False                            # write a FITS file to run in mcfost -- requires {grid.type: "mcfost"}

# The following settings require an installation of mcfost and pymcfost

mcfost:
    run_mcfost: False                            # generate velocity channels by running mcfost (boolean) -- requires {grid.type: "mcfost"} and {results.write_FITS: True}
    temp_star: 9250                              # temperature of the central star in Kelvin
    distance: 101.5                              # distance of system in parsecs
    v_max: 3.2                                   # maximum magnitude velocity for cube
    n_v: 40                                      # number of velocity channels for cube

pymcfost:
    pymcfost_plots: False                        # NOT IMPLEMENTED - create velocity channels plot using pymcfost (boolean)
    velocity_channels:
        [-1.6, -0.9, -0.2, 0.2, 0.9, 1.6]        # NOT IMPLEMENTED - velocity channels to be plotted by pymcfost -- must exist in cube generated
    beam: 0                                      # NOT IMPLEMENTED - beam size
    obs_dir: None                                # NOT IMPLEMENTED - directory of observations to plot
    sim_dir: None                                # NOT IMPLEMENTED - directory of simulation to plot (must be already run through mcfost)
    v_system: 5.8                                # NOT IMPLEMENTED - systemic velocity of the system

# Don't change below parameters unless you know what you are doing

physical:
    adiabatic_index: 1.6666667                   # adiabatic index
    damping_malpha: 0                            # artificial damping

numerical:
    CFL: 0.5                                     # CFL safety factor for Godunov scheme
    scale_box: 1.0                               # scale factor for linear regime box side length -- default is 1
    scale_box_ang: 1.0                           # scale factor for linear regime box angular extend
